<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Veroniques-MacBook-Air.local" failures="1" tests="2" name="PageObjectModel_Project" time="12.766" errors="0" timestamp="2022-07-28T15:44:30 EEST">
  <testcase classname="selenium.NewPostTest" name="testLoginPage" time="2.951">
    <skipped/>
  </testcase> <!-- testLoginPage -->
  <testcase classname="selenium.NewPostTest" name="testLoginPage" time="0.779">
    <failure type="java.lang.AssertionError" message="expected [Creation of post successful!] but found [Creation of post failed!
Successful login!]">
      <![CDATA[java.lang.AssertionError: expected [Creation of post successful!] but found [Creation of post failed!
Successful login!]
at selenium.NewPostTest.testLoginPage(NewPostTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testLoginPage -->
</testsuite> <!-- PageObjectModel_Project -->
